name: Deploy to S3+Cloudfront (dev)

on:
  push:
    branches:
      - dev # Deploy when pushing to the dev branch
  workflow_dispatch: # manual trigger from GitHub UI

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      id-token: write # Required for OIDC
      contents: read

    env:
      VITE_FRONTEND_URL: https://mmh-dev.theexpertscloud.com
      VITE_BACKEND_URL: https://mmh-dev-backend.theexpertscloud.com/api

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '22'
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Build React.js app
        run: npm run build

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v6
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME_GITHUB }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Sync static assets with long cache
        run: |
          aws s3 sync ./build s3://${{ secrets.DEV_S3_BUCKET }} \
            --delete \
            --cache-control "public,max-age=31536000,immutable" \
            --acl public-read

      - name: Upload index.html with no-cache
        run: |
          aws s3 cp ./build/index.html s3://${{ secrets.DEV_S3_BUCKET }}/index.html \
            --cache-control "no-cache,no-store,must-revalidate" \
            --acl public-read

      - name: Invalidate CloudFront
        run: |
          aws cloudfront create-invalidation --distribution-id ${{ secrets.DEV_AWS_CLOUDFRONT_DISTRIBUTION_ID }} --paths "/*"
